INSERT into Team VALUES
	(101, "ANA", "Anaheim Ducks", "https://upload.wikimedia.org/wikipedia/en/thumb/7/72/Anaheim_Ducks.svg/330px-Anaheim_Ducks.svg.png", "1993"),
	(102, "ARI", "Arizona Coyotes", "https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Arizona_Coyotes_logo_%282021%29.svg/330px-Arizona_Coyotes_logo_%282021%29.svg.png", "1972"),
	(103, "BOS", "Boston Bruins", "https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Boston_Bruins.svg/800px-Boston_Bruins.svg.png", "1924"),
	(104, "BUF", "Buffalo Sabres", "https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Buffalo_Sabres_Logo.svg/330px-Buffalo_Sabres_Logo.svg.png", "1970"),
	(105, "CAR", "Carolina Hurricanes", "https://upload.wikimedia.org/wikipedia/en/thumb/3/32/Carolina_Hurricanes.svg/330px-Carolina_Hurricanes.svg.png", "1972"),
	(106, "CBJ", "Columbus Blue Jackets", "https://upload.wikimedia.org/wikipedia/en/thumb/5/5d/Columbus_Blue_Jackets_logo.svg/330px-Columbus_Blue_Jackets_logo.svg.png", "2000"),
	(107, "CGY", "Calgary Flames", "https://upload.wikimedia.org/wikipedia/en/thumb/6/61/Calgary_Flames_logo.svg/330px-Calgary_Flames_logo.svg.png", "1972"),
	(108, "CHI", "Chicago Blackhawks", "https://upload.wikimedia.org/wikipedia/en/thumb/2/29/Chicago_Blackhawks_logo.svg/330px-Chicago_Blackhawks_logo.svg.png", "1926"),
	(109, "COL", "Colorado Avalanche", "https://upload.wikimedia.org/wikipedia/en/thumb/4/45/Colorado_Avalanche_logo.svg/330px-Colorado_Avalanche_logo.svg.png", "1972"),
	(110, "DAL", "Dallas Stars", "https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/Dallas_Stars_logo_%282013%29.svg/330px-Dallas_Stars_logo_%282013%29.svg.png", "1967"),
	(111, "DET", "Detroit Red Wings", "https://upload.wikimedia.org/wikipedia/en/thumb/e/e0/Detroit_Red_Wings_logo.svg/330px-Detroit_Red_Wings_logo.svg.png", "1926"),
	(112, "EDM", "Edmonton Oilers", "https://upload.wikimedia.org/wikipedia/en/thumb/4/4d/Logo_Edmonton_Oilers.svg/330px-Logo_Edmonton_Oilers.svg.png","1972"),
	(113, "FLA", "Florida Panthers", "https://upload.wikimedia.org/wikipedia/en/thumb/4/43/Florida_Panthers_2016_logo.svg/330px-Florida_Panthers_2016_logo.svg.png", "1993"),
	(114, "LAK", "Los Angeles Kings", "https://upload.wikimedia.org/wikipedia/en/thumb/6/63/Los_Angeles_Kings_logo.svg/330px-Los_Angeles_Kings_logo.svg.png", "1967"),
	(115, "MIN", "Minnesota Wild", "https://upload.wikimedia.org/wikipedia/en/thumb/1/1b/Minnesota_Wild.svg/330px-Minnesota_Wild.svg.png", "2000"),
	(116, "MTL", "Montreal Canadiens", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Montreal_Canadiens.svg/330px-Montreal_Canadiens.svg.png","1909"),
	(117, "NJD", "New Jersey Devils", "https://upload.wikimedia.org/wikipedia/en/thumb/9/9f/New_Jersey_Devils_logo.svg/330px-New_Jersey_Devils_logo.svg.png", "1974"),
	(118, "NSH", "Nashville Predators", "https://upload.wikimedia.org/wikipedia/en/thumb/9/9c/Nashville_Predators_Logo_%282011%29.svg/330px-Nashville_Predators_Logo_%282011%29.svg.png", "1998"),
	(119, "NYI", "New York Islanders", "https://upload.wikimedia.org/wikipedia/en/thumb/4/42/Logo_New_York_Islanders.svg/330px-Logo_New_York_Islanders.svg.png", "1972"),
	(120, "NYR", "New York Rangers", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/New_York_Rangers.svg/330px-New_York_Rangers.svg.png", "1926"),
	(121, "OTT", "Ottawa Senators", "https://upload.wikimedia.org/wikipedia/en/thumb/b/b2/Ottawa_Senators_2020-2021_logo.svg/330px-Ottawa_Senators_2020-2021_logo.svg.png", "1992"),
	(122, "PHI", "Philadelphia Flyers", "https://upload.wikimedia.org/wikipedia/en/thumb/d/dc/Philadelphia_Flyers.svg/330px-Philadelphia_Flyers.svg.png", "1967"),
	(123, "PIT", "Pittsburgh Penguins", "https://upload.wikimedia.org/wikipedia/en/thumb/c/c0/Pittsburgh_Penguins_logo_%282016%29.svg/330px-Pittsburgh_Penguins_logo_%282016%29.svg.png", "1967"),
	(124, "SEA", "Seattle Kraken", "https://upload.wikimedia.org/wikipedia/en/thumb/4/48/Seattle_Kraken_official_logo.svg/330px-Seattle_Kraken_official_logo.svg.png", "2021"),
	(125, "SJS", "San Jose Sharks", "https://upload.wikimedia.org/wikipedia/en/thumb/3/37/SanJoseSharksLogo.svg/330px-SanJoseSharksLogo.svg.png", "1991"),
	(126, "STL", "St. Louis Blues", "https://upload.wikimedia.org/wikipedia/en/thumb/e/ed/St._Louis_Blues_logo.svg/330px-St._Louis_Blues_logo.svg.png", "1967"),
	(127, "TBL", "Tampa Bay Lightning", "https://upload.wikimedia.org/wikipedia/en/thumb/2/2f/Tampa_Bay_Lightning_Logo_2011.svg/330px-Tampa_Bay_Lightning_Logo_2011.svg.png", "1992"),
	(128, "TOR", "Toronto Maple Leafs", "https://upload.wikimedia.org/wikipedia/en/thumb/b/b6/Toronto_Maple_Leafs_2016_logo.svg/330px-Toronto_Maple_Leafs_2016_logo.svg.png", "1917"),
	(129, "VAN", "Vancouver Canucks", "https://upload.wikimedia.org/wikipedia/en/thumb/3/3a/Vancouver_Canucks_logo.svg/330px-Vancouver_Canucks_logo.svg.png", "1945"),
	(130, "VGK", "Vegas Golden Knights", "https://upload.wikimedia.org/wikipedia/en/thumb/a/ac/Vegas_Golden_Knights_logo.svg/330px-Vegas_Golden_Knights_logo.svg.png", "2017"),
	(131, "WPG", "Winnipeg Jets", "https://upload.wikimedia.org/wikipedia/en/thumb/9/93/Winnipeg_Jets_Logo_2011.svg/330px-Winnipeg_Jets_Logo_2011.svg.png", "1999"),
	(132, "WSH", "Washington Capitals", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Washington_Capitals.svg/330px-Washington_Capitals.svg.png", "1974");