INSERT into Team VALUES
	(197, 'ANA', 'Anaheim Ducks', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/72/Anaheim_Ducks.svg/330px-Anaheim_Ducks.svg.png', '1993', 'Honda Center'),
	(198, 'ARI', 'Arizona Coyotes', 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Arizona_Coyotes_logo_%282021%29.svg/330px-Arizona_Coyotes_logo_%282021%29.svg.png', '1972', 'Mullett Arena'),
	(199, 'BOS', 'Boston Bruins', 'https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Boston_Bruins.svg/800px-Boston_Bruins.svg.png', '1924', 'TD Garden'),
	(200, 'BUF', 'Buffalo Sabres', 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Buffalo_Sabres_Logo.svg/330px-Buffalo_Sabres_Logo.svg.png', '1970', 'KeyBank Center'),
	(201, 'CAR', 'Carolina Hurricanes', 'https://upload.wikimedia.org/wikipedia/en/thumb/3/32/Carolina_Hurricanes.svg/330px-Carolina_Hurricanes.svg.png', '1972', 'PNC Arena'),
	(202, 'CBJ', 'Columbus Blue Jackets', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5d/Columbus_Blue_Jackets_logo.svg/330px-Columbus_Blue_Jackets_logo.svg.png', '2000', 'Nationwide Arena'),
	(203, 'CGY', 'Calgary Flames', 'https://upload.wikimedia.org/wikipedia/en/thumb/6/61/Calgary_Flames_logo.svg/330px-Calgary_Flames_logo.svg.png', '1972', 'Scotiabank Saddledome'),
	(204, 'CHI', 'Chicago Blackhawks', 'https://upload.wikimedia.org/wikipedia/en/thumb/2/29/Chicago_Blackhawks_logo.svg/330px-Chicago_Blackhawks_logo.svg.png', '1926', 'United Center'),
	(205, 'COL', 'Colorado Avalanche', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/45/Colorado_Avalanche_logo.svg/330px-Colorado_Avalanche_logo.svg.png', '1972', 'Ball Arena'),
	(206, 'DAL', 'Dallas Stars', 'https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/Dallas_Stars_logo_%282013%29.svg/330px-Dallas_Stars_logo_%282013%29.svg.png', '1967', 'American Airlines Center'),
	(207, 'DET', 'Detroit Red Wings', 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e0/Detroit_Red_Wings_logo.svg/330px-Detroit_Red_Wings_logo.svg.png', '1926', 'Little Caesars Arena'),
	(208, 'EDM', 'Edmonton Oilers', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4d/Logo_Edmonton_Oilers.svg/330px-Logo_Edmonton_Oilers.svg.png','1972', 'Rogers Place'),
	(209, 'FLA', 'Florida Panthers', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/43/Florida_Panthers_2016_logo.svg/330px-Florida_Panthers_2016_logo.svg.png', '1993', 'FLA Live Arena'),
	(210, 'LAK', 'Los Angeles Kings', 'https://upload.wikimedia.org/wikipedia/en/thumb/6/63/Los_Angeles_Kings_logo.svg/330px-Los_Angeles_Kings_logo.svg.png', '1967', 'Crypto.com Arena'),
	(211, 'MIN', 'Minnesota Wild', 'https://upload.wikimedia.org/wikipedia/en/thumb/1/1b/Minnesota_Wild.svg/330px-Minnesota_Wild.svg.png', '2000', 'Xcel Energy Center'),
	(212, 'MTL', 'Montreal Canadiens', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Montreal_Canadiens.svg/330px-Montreal_Canadiens.svg.png','1909', 'Bell Centre'),
	(213, 'NJD', 'New Jersey Devils', 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9f/New_Jersey_Devils_logo.svg/330px-New_Jersey_Devils_logo.svg.png', '1974', 'Prudential Center'),
	(214, 'NSH', 'Nashville Predators', 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9c/Nashville_Predators_Logo_%282011%29.svg/330px-Nashville_Predators_Logo_%282011%29.svg.png', '1998', 'Bridgestone Arena'),
	(215, 'NYI', 'New York Islanders', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/42/Logo_New_York_Islanders.svg/330px-Logo_New_York_Islanders.svg.png', '1972', 'UBS Arena'),
	(216, 'NYR', 'New York Rangers', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/New_York_Rangers.svg/330px-New_York_Rangers.svg.png', '1926', 'Madison Square Garden'),
	(217, 'OTT', 'Ottawa Senators', 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b2/Ottawa_Senators_2020-2021_logo.svg/330px-Ottawa_Senators_2020-2021_logo.svg.png', '1992', 'Canadian Tire Centre'),
	(218, 'PHI', 'Philadelphia Flyers', 'https://upload.wikimedia.org/wikipedia/en/thumb/d/dc/Philadelphia_Flyers.svg/330px-Philadelphia_Flyers.svg.png', '1967', 'Wells Fargo Center'),
	(219, 'PIT', 'Pittsburgh Penguins', 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c0/Pittsburgh_Penguins_logo_%282016%29.svg/330px-Pittsburgh_Penguins_logo_%282016%29.svg.png', '1967', 'PPG Paints Arena'),
	(220, 'SEA', 'Seattle Kraken', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/48/Seattle_Kraken_official_logo.svg/330px-Seattle_Kraken_official_logo.svg.png', '2021', 'Climate Pledge Arena'),
	(221, 'SJS', 'San Jose Sharks', 'https://upload.wikimedia.org/wikipedia/en/thumb/3/37/SanJoseSharksLogo.svg/330px-SanJoseSharksLogo.svg.png', '1991', 'SAP Center'),
	(222, 'STL', 'St. Louis Blues', 'https://upload.wikimedia.org/wikipedia/en/thumb/e/ed/St._Louis_Blues_logo.svg/330px-St._Louis_Blues_logo.svg.png', '1967', 'Enterprise Center'),
	(223, 'TBL', 'Tampa Bay Lightning', 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2f/Tampa_Bay_Lightning_Logo_2011.svg/330px-Tampa_Bay_Lightning_Logo_2011.svg.png', '1992', 'Amalie Arena'),
	(224, 'TOR', 'Toronto Maple Leafs', 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b6/Toronto_Maple_Leafs_2016_logo.svg/330px-Toronto_Maple_Leafs_2016_logo.svg.png', '1917', 'Scotiabank Arena'),
	(225, 'VAN', 'Vancouver Canucks', 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3a/Vancouver_Canucks_logo.svg/330px-Vancouver_Canucks_logo.svg.png', '1945', 'Rogers Arena'),
	(226, 'VGK', 'Vegas Golden Knights', 'https://upload.wikimedia.org/wikipedia/en/thumb/a/ac/Vegas_Golden_Knights_logo.svg/330px-Vegas_Golden_Knights_logo.svg.png', '2017', 'T-Mobile Arena'),
	(227, 'WPG', 'Winnipeg Jets', 'https://upload.wikimedia.org/wikipedia/en/thumb/9/93/Winnipeg_Jets_Logo_2011.svg/330px-Winnipeg_Jets_Logo_2011.svg.png', '1999', 'Canada Life Centre'),
	(228, 'WSH', 'Washington Capitals', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Washington_Capitals.svg/330px-Washington_Capitals.svg.png', '1974', 'Capital One Arena');
